[build]
  base = "vision-venture-site"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://sammeske.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"

